go:
    # Whenever the Go version is updated here, .travis.yml and
    # .circle/config.yml should also be updated.
    version: 1.12
repository:
    path: github.com/JammyT/pushgateway
build:
    flags: -mod=vendor -a -tags netgo
    ldflags: |
        -X github.com/JammyT/common/version.Version={{.Version}}
        -X github.com/JammyT/common/version.Revision={{.Revision}}
        -X github.com/JammyT/common/version.Branch={{.Branch}}
        -X github.com/JammyT/common/version.BuildUser={{user}}@{{host}}
        -X github.com/JammyT/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - NOTICE
